rootfs_configs:
  buster:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - 'arm64'
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove:
      - '*networkd*'
      - '*resolved*'
      - tar
      - patch
      - dir
      - partx
      - find
    script: ""
  busterV2:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - 'armel'
