rootfs_configs:
  buster:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - 'amd64'
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - klibc-utils
      - libext2fs2
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - sensible-utils
    extra_files_remove:
      - '*networkd*'
      - '*resolved*'
      - tar
      - patch
      - dir
      - partx
      - find
    script: ""
  buster-v4l2:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - 'armhf'
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
    script: "scripts/buster-v4l2.sh"
    test_overlay: "overlays/v4l2"
  buster-igt:
    rootfs_type: debos
    debian_release: buster
    arch_list:
      - 'amd64'
    extra_packages:
      - libcairo2
      - libdw1
      - libglib2.0-0
      - libpciaccess0
      - libprocps7
      - libudev1
      - libunwind8
    extra_packages_remove:
      - bash
      - e2fslibs
      - e2fsprogs
      - fonts-dejavu-core
      - klibc-utils
      - libext2fs2
      - libgio3.0-cil
      - libgnutls30
      - libklibc
      - libncursesw6
      - libp11-kit0
      - libunistring2
      - libx11-data
      - sensible-utils
    extra_files_remove:
      - '*networkd*'
      - '*resolved*'
      - tar
      - patch
      - dir
      - partx
      - find
    script: "scripts/buster-igt.sh"
    test_overlay: "overlays/igt"
